### ISSUE TITLE
Clear Name and VAPID Key fields after adding new Push Application

### ISSUE THREAD

**Issue by pdehaan** [groovecoder/push-dev-dashboard#103]
### Steps to reproduce:
1. Go to https://moz-push-dash.herokuapp.com/push/apps/
2. Register a new Push Application.
3. Click the **[Add Push Application]** button.
### Actual results:

The `Name` and `VAPID Key` text fields aren't cleared, making it easy to re-add the push application again by mistake.

![push_dashboard_and_new_issue_ _mozilla-services_push-dev-dashboard_and_push-dev-dashboard_tox_ini_at_master_ _mozilla-services_push-dev-dashboard](https://cloud.githubusercontent.com/assets/557895/13689886/06911b48-e6e1-11e5-85a8-ead99ca9583f.png)
**Figure 1:** Note the fields aren't cleared, even though they were added above.
### Expected results:

After successfully submitting the form, clear the fields.

**Comment by openjck** [comment]
Good catch, thanks!
