### ISSUE TITLE
Implement https for *.deis.dev.mozaws.net

### ISSUE THREAD

**Issue by groovecoder** [groovecoder/push-dev-dashboard#119]
To enable pontoon (https://github.com/mozilla-services/push-dev-dashboard/issues/99), we need to serve the site over HTTPS. To dev and test this, we need to add https for http://dev-dashboard.deis.dev.mozaws.net/.

@oremj - what's the process for getting an SSL cert for *.deis.dev.mozaws.net? And/or do we already have a cert for *.dev.mozaws.net that we can re-use?

**Comment by oremj** [comment]
We have a cert for *.dev.mozaws.net, but it won't work for *.apps.dev.mozaws.net. Who hosts the deis cluster @ apps.dev.mozaws.net?

**Comment by groovecoder** [comment]
I set it up a few weeks ago. Ben mentioned he may also use it for some part(s) of the push service. It would be nice to secure *.apps.dev.mozaws.net - that way any app we deploy to it will be HTTPS.

**Comment by oremj** [comment]
Can you use let's encrypt or AWS certificate manager? Also, can you change the name? We may need to use the app or apps subdomain for other purposes.

**Comment by groovecoder** [comment]
How about deis.dev.mozaws.net ... so then an app like this would live at https://dev-dashboard.deis.dev.mozaws.net? (Though that means the controller is at the clumsy https://deis.deis.dev.mozaws.net - such meta.)

**Comment by oremj** [comment]
Sure you can take deis.dev.

**Comment by groovecoder** [comment]
Okay, I moved to http://dev-dashboard.deis.dev.mozaws.net/

I already see a AWS Certificate request for *.deis.dev.mozaws.net in the AWS Certificate Management Console. @oremj - did you start that already? It says that it needs validation ... from hostmaster@mozilla.com?

**Comment by groovecoder** [comment]
@oremj - any progress on this? Looks like the certificate request timed out? :cry: 

```
Timed out
Certificate requests time out after 72 hours if they are not approved. Delete this request and start over if you want a certificate. Learn more.
Status
Timed out
```

**Comment by oremj** [comment]
It's going to be a few days. That domain is currently in the middle of a transfer.

**Comment by groovecoder** [comment]
That should be fine. The sooner we get https enabled, the sooner we can get our l10n community to translate the site using pontoon. Next week would be good, as we'd like to go live as close to Apr 4 as possible, and it would be great to go live with some languages already 100% translated.

**Comment by oremj** [comment]
The domain transfer happened faster than expected. The cert is ready for use. To make us of it, you'll need to place an ELB in front of your deis instance(s).

**Comment by groovecoder** [comment]
Cool, thanks. I set up Secure TCP with the certificate on deis-DeisWebELB-1DYAXPDIIJVIH.

**Comment by groovecoder** [comment]
Yay! https://dev-dashboard.deis.dev.mozaws.net/en/

**Comment by groovecoder** [comment]
@oremj - is there a way to make the ELB re-direct all HTTP traffic to HTTPS now that it's supported?

**Comment by oremj** [comment]
No, you'd need to set up a redirector on a different port.

**Comment by groovecoder** [comment]
I searched around a bit for AWS docs and couldn't find that. Can you link me to something for it?

**Comment by oremj** [comment]
You just need to set up a service that returns 302s on a port and set up a listener on port 80 which sends traffic to that instance/port.
