### ISSUE TITLE
Localizability issues in the current .po file

### ISSUE THREAD

**Issue by flodolo** [groovecoder/push-dev-dashboard#133]
```
#: push/templates/push/landing.html:16
msgid "Sign in"
msgstr ""

#: push/templates/push/landing.html:16
msgid "to track your push applications"
msgstr ""
```

This makes assumption on the structure of the phrase, this should be a single string like `<a>Sign</a> to track your push applications`, so that other languages can move the link around.

```
#: push/templates/push/list.html:97
msgid ""
"The public key that the application server sends for VAPID JWT validation. "
"This should be the exact value sent in the \\"
msgstr ""
```

This looks like another concatenation.

```
#: templates/includes/fxa_sign_in_link.html:4
msgid "Sign in with <i class=\"fa fa-firefox\"></i> Firefox Account "
msgstr ""
```

What's the use for that <i> tag?

**Comment by groovecoder** [comment]
@flodolo - can you verify that https://github.com/mozilla-services/push-dev-dashboard/blob/master/locale/django.pot now includes all these fixes?

**Comment by flodolo** [comment]
Yes, they've all been fixed.
