### ISSUE TITLE
Web Performance Issues on home page

### ISSUE THREAD

**Issue by groovecoder** [groovecoder/push-dev-dashboard#146]
- [x] Optimize the following images to reduce their size by 60.3KiB (25% reduction).
  - Losslessly compressing screenshot.png could save 54.1KiB (36% reduction).
  - Losslessly compressing firefox-logo.png could save 6.3KiB (7% reduction). 
  - https://github.com/mozilla-services/push-dev-dashboard/pull/150
- [x] Redirect users using the HTTP version of the page to the HTTPs version.
  - https://github.com/mozilla-services/push-dev-dashboard/issues/149
- [x] It is recommended to put page keywords at least in h1 and h2 tags. Search engines use h1, h2 and h3 tags for SEO. Others tags (h4, h5 and h6) just help you to enhance the content. This page contains: 1 `<h2>` element(s)
  - https://github.com/mozilla-services/push-dev-dashboard/pull/151
- [x] No <meta> description found on this page. You should provide a <meta> description.
  - https://github.com/mozilla-services/push-dev-dashboard/pull/151
- [x] The Content Security Policy is missing
  - https://github.com/mozilla-services/push-dev-dashboard/issues/155

**Comment by openjck** [comment]
Great ideas. I'd recommend we use Gulp for optimizing the images. Having a good automation foundation from the start should make it easier and less error-prone.

**Comment by groovecoder** [comment]
With gulp automation, would we still check the compressed images into the repo?

**Comment by groovecoder** [comment]
Also, since our other front-end assets are compiled & compressed via django-pipeline, I almost prefer to [write a custom django-pipeline compressor](https://django-pipeline.readthedocs.org/en/latest/compressors.html#write-your-own-compressor-class) for images than to add a separate build tool for just those types of assets.

**Comment by openjck** [comment]
> Also, since our other front-end assets are compiled & compressed via django-pipeline, I almost prefer to write a custom django-pipeline compressor for images than to add a separate build tool for just those types of assets.

I would be up for that. The automation is the important part, moreso than the tool we use.

**Comment by groovecoder** [comment]
All these sub-tasks are done now.
