### ISSUE TITLE
Add a button to copy the token to sign to the clipboard

### ISSUE THREAD

**Issue by marco-c** [groovecoder/push-dev-dashboard#182]

**Comment by groovecoder** [comment]
I've tried a few different approaches to do this with just JS. This one seems close, but still gets an error: `document.execCommand('cut'/'copy') was denied because it was not called from inside a short running user-generated event handler.`
HTML:

```
<a id="copy-token-link"><i class="fa fa-clipboard" data-clipboard-text="{{ app.vapid_key_token }}"></i></a>
```

CSS:

```
#copy-token-link {
    margin: 1em;
}
```

JavaScript:

```
(function(win, doc, $) {
    'use strict';

    var clipData;

    var _copy = function(e) {
        e.clipboardData.setData("text/plain", clipData);
    };

    $('#copy-token-link').on('click', function(e) {
        dashboard.analytics.trackEvent({
            category: 'Push Application',
            action: 'copy token'
        });
        clipData = e.target.getAttribute("data-clipboard-text");
        document.addEventListener("copy", _copy, false)
        document.execCommand("copy", false, null);
        document.removeEventListener("copy", _copy, false)
    });

})(window, document, jQuery);
```

Even though it's in a click handler.

The other - easier - option is to change the token to an input element and pre-select it so the user can just Ctrl/Cmd+C to copy it.

**Comment by marco-c** [comment]
Interesting, I wonder why.
How does the GitHub button to copy the SHA of a commit work?

**Comment by groovecoder** [comment]
Hmm ... I'd have to dig into it. Looks like they're using [zeroclipboard](https://github.com/zeroclipboard/zeroclipboard), which I had found but decided not to use or try since it looked like it was using Flash. But I just disabled Flash and the copy still worked. So, maybe I'll try that ...

**Comment by groovecoder** [comment]
Hmm ... they seem to be using something called js-zeroclipboard, which I can't find. 😢 And I can't find that library.

**Comment by marco-c** [comment]
There's a discussion here: https://groups.google.com/forum/#!topic/mozilla.dev.platform/oWhmLMvGAD0

Maybe there's some info to debug the problem?

**Comment by marco-c** [comment]
There's also an example on MDN (https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand#Example), I don't know if you've already seen it.

**Comment by groovecoder** [comment]
I've poked around a few of them ... just need to strip out all of the extra code from the core `execCommand`.
