### ISSUE TITLE
add Google Analytics events for dashboard engagement metrics

### ISSUE THREAD

**Issue by groovecoder** [groovecoder/push-dev-dashboard#194]
![dashboard-metrics-funnel](https://cloud.githubusercontent.com/assets/71928/14656364/c3c72844-064c-11e6-9c4b-13cc725f64ea.png)

Also, capture public keys for the user when they sign in so we can correlate with push server metrics itself

**Comment by groovecoder** [comment]
@bbangert - I've forgotten what we meant by this. 😢 Do you remember?

**Comment by groovecoder** [comment]
These are the metrics I'm planning to record - either with the built-in GA tracking and/or by adding custom event tracking. (cc @edmoz)
https://docs.google.com/drawings/d/1uZI8jAo7_jf-gZxe8qeOGaYNGfVxn-edgAsSpgmS8b4/edit?ts=5716a2a0

**Comment by bbangert** [comment]
GA should let you track those. I mainly meant that you should use the custom User ID feature so that its possible to correlate GA sessions with the actual Dashboard account, per:
https://support.google.com/analytics/answer/3123663
