### ISSUE TITLE
create a "signed in successfully" event

### ISSUE THREAD

**Issue by clarkbw** [groovecoder/push-dev-dashboard#215]
**GA micro goal**: _Successfully Signed In_

One of our micro goals for GA should be that a person clicked the "Sign In" button (creating a "Sign In" event) and then successfully "Signed In" to the application. This is the first of many micro goals along the way to completing our marcro goal. With this data we'll know the drop off rate of users who sign in.

Currently the site redirects to the main page `/` such that we can't use a page location as a good indicator for success.  And I'm assuming GA doesn't exist on the redirects involved post-OAuth where we could have a destination as the goal. 

**New Account?**
It would be useful to capture if these users are creating a new Firefox Account or signing in with an existing Firefox Account.  This extra information would help us understand what percentage of developers already have a Firefox account.  In the future we may want to recommend that developers create a new Firefox Account using a group email address instead of a personal one and at that time this metric will give us a decent baseline for the change.

**Comment by groovecoder** [comment]
To track "Finished sign-in" on MDN, we use a `data-login-service` attribute and `localStorage` to keep track of sign-in state across all page visits. I'll re-implement the same thing here to create a "Successfully Signed In" GA event & goal.

**Comment by clarkbw** [comment]
Added Goal 1 to capture this, watching for `/(Started|Finished) sign-in/` actions in the `Auth` category.
