### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by groovecoder** [groovecoder/push-dev-dashboard#230]
@clarkbw - Decide which favicon to use ...

![firefox-logo](https://cloud.githubusercontent.com/assets/71928/15397833/1a5b6ce4-1da7-11e6-9c29-d6294155c8d5.png)

![mozilla-services](https://cloud.githubusercontent.com/assets/71928/15397841/1e7224f8-1da7-11e6-8382-7de735e91735.png)

![favicon](https://cloud.githubusercontent.com/assets/71928/15397852/27c95652-1da7-11e6-8806-245874cca73e.png)

**Comment by clarkbw** [comment]
@groovecoder there's no services group favicon?

I'd go with the M for now until we have something else.

**Comment by groovecoder** [comment]
I dug up that second one because it was for "Weave" ... which became Sync, the logo of which is what we use for [the mozilla-service github org](https://github.com/mozilla-services/).

So, the weave one seems like it could fit the larger services group ... ?

**Comment by clarkbw** [comment]
> what we use for the mozilla-service github org.

That one and the one above are different.  Let's use the one from the github group.

**Comment by ghost** [comment]
We need a catchy logo for Push. :wink:
