### ISSUE TITLE
A few warnings in the dev console

### ISSUE THREAD

**Issue by pdehaan** [groovecoder/push-dev-dashboard#69]
Chrome is giving me a few error looking things in the Developer console, mainly seems to be about CORs and font loading from datadog.

![push_dashboard_and_push_dashboard_and_push_dashboard_and_event_registration__event__1126701_-_session__1_](https://cloud.githubusercontent.com/assets/557895/13479525/5dcd1ff2-e08c-11e5-928d-e5a7b433f9c9.png)

Firefox seems to give me literally hundreds of warnings in my console, but 99.9% look like they're coming from minified jquery, newrelic, zurb foundation, and datadog libs (but they're pretty difficult to filter out to see just moz-push-dash errors/warnings).

![push_dashboard_and_event_registration__event__1126701_-_session__1__and_privacy_policy_ _privacy___terms_ _google_and_new_tab](https://cloud.githubusercontent.com/assets/557895/13479600/f5f76df0-e08c-11e5-9557-a9da263030e5.png)

**Comment by openjck** [comment]
There's one error in the Firefox output that we should fix. The Chrome errors look like they're on Datadog's end.

@groovecoder Where have you been escalating Datadog issues? I see lots of repos on GitHub, but I'm not sure which one relates to our widget.
