### ISSUE TITLE
Why FxA stable instead of prod?

### ISSUE THREAD

**Issue by pdehaan** [groovecoder/push-dev-dashboard#70]
Just curious, but why does the Push Dashboard use the https://stable.dev.lcip.org/ instead of using the production FxA site, https://accounts.firefox.com/, (and therefore making users sign up to FxA in two places).

**Comment by groovecoder** [comment]
The dashboard instances deployed on [heroku](http://moz-push-dash.herokuapp.com/) and on [AWS](http://dev-dashboard.apps.dev.mozaws.net/) are dev/staging environments, so they use the dev/staging FxA OAuth endpoint.

The FxA endpoint is configured in an environment variable though, so when we deploy to production, we will easily configure it to use accounts.firefox.com OAuth endpoint.
