### ISSUE TITLE
End-to-end staging test

### ISSUE THREAD

**Issue by groovecoder** [groovecoder/push-dev-dashboard#87]
Needs
- [x] Live stage autopush server
- [x] Live stage messages API using live stage autopush server
- [x] Demo app sending messages with VAPID to the live stage autopush server
- [x] Point the stage dashboard at the stage messages API

**Comment by edwindotcom** [comment]
If you have the stage autopush URL, I can drop that into my browser's dom.push.serverURL pref and test this... I think

**Comment by groovecoder** [comment]
https://github.com/mozilla-services/push-service/issues/25 is for live staging autopush environment.

**Comment by groovecoder** [comment]
This is done. Instructions for end-to-end testing:
1. In [`about:config`](about:config), set:
   - `dom.push.serverURL` = `wss://benpushstack-1704054003.dev.mozaws.net/`
2. Go to https://mozilla-services.github.io/WebPushDataTestPage/
   - Make sure you Add VAPID headers
   - When you get to the "Push Dashboard" section, follow its instructions. If it's unclear **please file an issue here on what could make it more clear** - this is the trickiest and nastiest part of the UX of the dashboard so any and all ideas to improve it are welcome.
   - After you validate the key on the dashboard, you should see the app details page show VAPID Key Status = "recording", but there are not messages, so ...
3. Return to the WebPushDataTestPage tab to generate the content, and send the data via the `curl` command. (The stage push server is not HTTPS, so the HTTPS page won't let you POST to it.)
   - You should get the push notification 🔔 
4. After a couple minutes, reload the app details page on the dashboard. You should see your message show up in the list.
5. 🎉

**Comment by groovecoder** [comment]
@bbangert - you said you were going to ask someone to have them dump staging push logs to S3 every minute?

**Comment by bbangert** [comment]
Ah, for staging? I think @oremj has that running by having autopush in stage use firehose.
