### ISSUE TITLE
Name form field is ambiguious

### ISSUE THREAD

**Issue by edwindotcom** [groovecoder/push-dev-dashboard#92]
1. sign into fxa
2. look at 'Name' field

actual: "Name"

I'm not sure what to put in there.
I know i pass in this to generate my VAPID values:
audience:"https://mySite.com/"
subscriber: "mailto:MyUsername@site.com"

Expected: "Application Name" so it's clear that it's neither the audience or subscriber values.

**Comment by groovecoder** [comment]
Thanks for the feedback.

**Comment by openjck** [comment]
I agree. We'll change it to _Application name_.
